# Generated by Django 5.1.2 on 2024-11-30 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_sys_firstname_user_sys_lastname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sys_acc_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='sys_acc_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sys_status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Suspended'), (2, 'Deleted')], default=0),
        ),
    ]
