# Generated by Django 5.1.2 on 2024-11-30 14:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booklist',
            fields=[
                ('id', models.BigAutoField(db_column='b_id', primary_key=True, serialize=False)),
                ('item_call_num', models.CharField(db_column='b_item_call_num', max_length=200, unique=True)),
                ('col_code', models.CharField(db_column='b_col_code', max_length=100)),
                ('barcode', models.CharField(db_column='b_barcode', max_length=55, unique=True)),
                ('itype', models.CharField(db_column='b_itype', max_length=100)),
                ('title', models.CharField(db_column='b_title', max_length=255)),
                ('author', models.CharField(db_column='b_author', max_length=255)),
                ('publishercode', models.CharField(db_column='b_publishercode', max_length=255)),
                ('date_accessioned', models.DateField(auto_now=True, db_column='b_date_accessioned')),
                ('isbn', models.CharField(db_column='b_isbn', max_length=20)),
                ('copy_num', models.IntegerField(db_column='b_copy_num', help_text='Copy number starting from 1', validators=[django.core.validators.MinValueValidator(1)])),
                ('volume', models.CharField(blank=True, db_column='b_volume', max_length=100, null=True)),
                ('edition_stmt', models.CharField(blank=True, db_column='b_edition_stmt', max_length=255, null=True)),
                ('subtitle', models.TextField(blank=True, db_column='b_subtitle', null=True)),
                ('paidfor', models.CharField(blank=True, db_column='b_paidfor', max_length=55, null=True)),
                ('price', models.DecimalField(db_column='b_price', decimal_places=2, max_digits=10)),
                ('bookseller_id', models.CharField(db_column='b_bookseller_id', max_length=55)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(db_column='inv_id', primary_key=True, serialize=False)),
                ('datetime_checked', models.DateTimeField(auto_now=True, db_column='inv_datetime_checked')),
                ('status', models.IntegerField(choices=[(1, 'Good Condition'), (2, 'No Barcode Tag'), (3, 'For Repair'), (4, 'For Disposal')], db_column='inv_status', default=1)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_inventory.booklist')),
            ],
            options={
                'ordering': ['-datetime_checked'],
            },
        ),
    ]
