# Generated by Django 5.1.2 on 2024-12-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Good Condition'), (2, 'No Barcode Tag'), (3, 'For Repair'), (4, 'For Disposal')], db_column='inv_status', null=True),
        ),
    ]
