# Generated by Django 5.1.2 on 2024-12-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_inventory', '0003_remove_booklist_publishercode_booklist_copyrightdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='price',
            field=models.DecimalField(blank=True, db_column='b_price', decimal_places=2, max_digits=10, null=True),
        ),
    ]
