# Generated by Django 5.1.2 on 2024-12-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_inventory', '0005_alter_booklist_date_accessioned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='copyrightdate',
            field=models.CharField(blank=True, db_column='b_copyrightdate', max_length=55),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='price',
            field=models.CharField(blank=True, db_column='b_price', max_length=55, null=True),
        ),
    ]
