# Generated by Django 5.1.2 on 2024-12-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_inventory', '0006_alter_booklist_copyrightdate_alter_booklist_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='copy_num',
            field=models.CharField(blank=True, db_column='b_copy_num', help_text='Copy number starting from 1', max_length=55),
        ),
    ]
