# Generated by Django 5.1.2 on 2024-12-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_inventory', '0007_alter_booklist_copy_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='barcode',
            field=models.CharField(db_column='b_barcode', max_length=55),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='item_call_num',
            field=models.CharField(db_column='b_item_call_num', max_length=200),
        ),
    ]
