# Generated by Django 5.1.2 on 2024-12-05 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_inventory', '0008_alter_booklist_barcode_alter_booklist_item_call_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='b_id',
            new_name='book',
        ),
    ]
