# Generated by Django 5.1.2 on 2024-12-06 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_inventory', '0009_rename_b_id_inventory_book'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.BigAutoField(db_column='h_id', primary_key=True, serialize=False)),
                ('datetime_checked', models.DateTimeField(auto_now=True, db_column='h_datetime_checked')),
                ('status', models.IntegerField(choices=[(1, 'Good Condition'), (2, 'No Barcode Tag'), (3, 'For Repair'), (4, 'For Disposal')], db_column='h_status', help_text='Status of the inventory at the time of review')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='admin_inventory.inventory')),
                ('reviewed_by', models.ForeignKey(db_column='h_reviewed_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime_checked'],
                'indexes': [models.Index(fields=['inventory'], name='admin_inven_invento_ab2aa3_idx'), models.Index(fields=['reviewed_by'], name='admin_inven_h_revie_db7cb0_idx')],
            },
        ),
    ]
