# Generated by Django 5.1.2 on 2024-12-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_inventory', '0010_inventoryhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryhistory',
            name='status',
            field=models.IntegerField(choices=[(1, 'Good Condition'), (2, 'No Barcode Tag'), (3, 'For Repair'), (4, 'For Disposal')], db_column='h_status'),
        ),
    ]
