---
name: Deploy to Server

# on:
#   workflow_run:
#     workflows: [Continuous Integration]
#     branches:
#       - main
#     types:
#       - completed

# on:
#   workflow_dispatch:
   
on:
  push:
    branches:
      - test/cicd

permissions:
  contents: read
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io

jobs:
  pull-from-server:
    name: Command server to pull and run Docker Image
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Setup Tailscale on Runner
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          audience: ${{ secrets.TS_AUDIENCE }}
          tags: tag:cicd
          ping: ${{ secrets.TS_SERVER_HOST }}
    
      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" >> ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          ssh-keyscan ${{ secrets.TS_SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Pull Codebase from Github
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.SSH_USER }}@${{ secrets.TS_SERVER_HOST }} "
            eval \"\$(ssh-agent -s)\"
            ssh-add '${{ TS_SERVER_KEYS_PATH }}'
            cd ${{ secrets.APP_DIR }}
            git pull
          "

      - name: (TEST) Pull image from GHCR
        run: |
          ssh -i ~/.ssh/deploy_key ${{ secrets.SSH_USER }}@${{ secrets.TS_SERVER_HOST }} "
            echo "${{ secrets.GITHUB_TOKEN }}" docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
            docker pull ${{ env.REGISTRY }}/${{ github.repository }}/armv7
          "
